-- 생성된 테이블 삭제하기 
DROP TABLE DEPARTMENT;
DROP TABLE EMPLOYEE;
DROP TABLE JDBC_TEST;
-- DEPARTMENT 테이블 생성
-- 데이터 정의어 : CREATE, DROP, ALTER 
CREATE TABLE DEPARTMENT (
	DEPTNO	NUMBER	NOT NULL,
	DEPTNAME	CHAR(10),
	FLOOR		NUMBER,
	PRIMARY KEY(DEPTNO)
);

--생성된 테이블에 데이터 입력 
--데이터 조작어 : INSERT, DELETE, UPDATE
INSERT INTO DEPARTMENT VALUES(1, '영업', 8);
INSERT INTO DEPARTMENT VALUES(2, '기획', 10);
INSERT INTO DEPARTMENT VALUES(3, '개발', 9);
INSERT INTO DEPARTMENT VALUES(4, '총무', 7);

-- EMPLOYEE 테이블 생성
CREATE TABLE EMPLOYEE (
	EMPNO	NUMBER	NOT NULL,
	EMPNAME	CHAR(10)	UNIQUE,
	TITLE	CHAR(10)	DEFAULT '사원',
	MANAGER	NUMBER,
	SALARY NUMBER	CHECK (SALARY < 6000000),
	DNO	NUMBER DEFAULT 1 CHECK (DNO IN (1,2,3,4)),
	PRIMARY KEY(EMPNO),
  FOREIGN KEY(MANAGER) REFERENCES EMPLOYEE(EMPNO),
	FOREIGN KEY(DNO) REFERENCES DEPARTMENT(DEPTNO) ON DELETE CASCADE
);

INSERT INTO EMPLOYEE VALUES(4377, '이성래', '사장', NULL, 5000000, 2);
INSERT INTO EMPLOYEE VALUES(3426, '박영권', '과장', 4377, 3000000, 1);
INSERT INTO EMPLOYEE VALUES(3011, '이수민', '부장', 4377, 4000000, 3);
INSERT INTO EMPLOYEE VALUES(3427, '최종철', '사원', 3011, 1500000, 3);
INSERT INTO EMPLOYEE VALUES(1003, '조민희', '과장', 4377, 3000000, 2);
INSERT INTO EMPLOYEE VALUES(2106, '김창섭', '대리', 1003, 2500000, 2);
INSERT INTO EMPLOYEE VALUES(1365, '김상원', '사원', 3426, 1500000, 1);

-- EMP_PLANNING 뷰 생성
CREATE VIEW EMP_PLANNING
AS
SELECT E.EMPNAME, E.TITLE, E.SALARY
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DNO=D.DEPTNO AND D.DEPTNAME='기획';

-- jdbc_test 테이블 생성
CREATE TABLE JDBC_TEST (
	username	VARCHAR2(12),
	email		VARCHAR2(30)
     
);
-- 생성된 테이블에 데이터 입력 
INSERT INTO JDBC_TEST VALUES('손창수', 'son@naver.com');
SELECT * FROM jdbc_test;
select username, email from jdbc_test;
DESC jdbc_test;

-- 데이터 사전 뷰(tab) : 데이터베이스 내에 존재하는 테이블과 표시
SELECT * FROM tab;

SELECT *
FROM tab;

-- 테이블의 구조 확인 : DESCRIBE(DESC)
DESCRIBE DEPARTMENT;
DESC DEPARTMENT;

-- DEPARTMENT 테이블의 내용 확인
SELECT * FROM DEPARTMENT;
SELECT * FROM EMPLOYEE;

-- PROJECT 테이블 생성
CREATE TABLE PROJECT
(
    Projnp NUMBER NOT NULL,
    Projname CHAR(15) NOT NULL,
    Budjet NUMBER
);

-- PROJECT 테이블을 수정(애트리뷰트 추가하고 싶을 경우)
-- 데이터 정의어 : CREATE, DROP, ALTER 
-- ALTER ~ ADD 
ALTER TABLE PROJECT ADD Manager NUMBER;
-- 방금 추가한 Manager 애트리뷰트를 삭제하기
-- ALTER ~ DROP COLUMN
ALTER TABLE PROJECT DROP COLUMN Mangager;










