-- 릴레이션 제거하고 싶을 경우 -> DROP TABLE 릴레이션이름; 
DROP TABLE DEPARTMENT; 
DROP TABLE EMPLOYEE;
-- DEPARTMENT 릴레이션과 EMPLOYEE 릴레이션의 생성
CREATE TABLE DEPARTMENT
    (DEPTNO NUMBER  NOT NULL,
     DEPTNAME   CHAR(10),
     FLOOR  NUMBER,
     PRIMARY KEY(DEPTNO));
--릴레이션 정의에서 다양한 제약조건을 명시해보기     
--애트리뷰트 제약조건 : NOT NULL, UNIQUE, DEFAULT, CHECK, PRIMARY KEY, FOREIGN KEY     
CREATE TABLE EMPLOYEE
    (EMPNO  NUMBER  NOT NULL,
     EMPNAME    CHAR(10) UNIQUE,
     TITLE  CHAR(10) DEFAULT '사원',
     MANAGER    NUMBER,
     SALARY     NUMBER CHECK (SALARY < 6000000),  
     DNO    NUMBER CHECK (DNO IN (1,2,3,4,5,6)),
--1,2,3,4,5,6 중 하나가 들어가고 만약에 부서번호 입력하지 않으면 1이 무조건 들어가게 된다.      
     PRIMARY KEY(EMPNO),
     FOREIGN KEY(MANAGER) REFERENCES EMPLOYEE(EMPNO),
     FOREIGN KEY(DNO) REFERENCES DEPARTMENT(DEPTNO)
             ON DELETE CASCADE);
--연쇄 삭제 


