-- 뷰 실습(한 릴레이션 위에서 뷰를 정의)
CREATE VIEW EMP_DNO3 (ENO, ENAME, TITLE)
AS SELECT EMPNO, EMPNAME, TITLE
FROM EMPLOYEE
WHERE DNO=3;

-- 뷰 실습 (두 릴레이션 위에서 뷰를 정의)

CREATE VIEW EMP_PLANNING
AS SELECT E.EMPNAME, E.TITLE, E.SALARY
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DNO = D.DEPTNO AND D.DEPTNAME = '기획';

--기획부에 근무하는 사원들 중에서 직책이 부장인 사원의 사원 이름과 급여를 검색하기
SELECT EMPNAME, SALARY
FROM EMP_PLANNING
WHERE TITLE = '부장';

-- 무결성 유지 -> WITH CHECK OPTION (조건 애트리뷰트를 수정할 수 없도록 함)
DROP VIEW EMP_DNO3;

CREATE VIEW EMP_DNO3 (ENO, DNO, ENAME, TITLE)
AS SELECT EMPNO, DNO, EMPNAME, TITLE
    FROM EMPLOYEE
    WHERE DNO=3
    WITH CHECK OPTION;
    
UPDATE EMP_DNO3
SET DNO=2
WHERE DNO=3427;

-- 실행결과 원하는 대로 안 됨 


--실습 : 사원 이름과 소속된 부서 이름이 출력되는 EMP_DEPT뷰를 생성하기
CREATE VIEW EMP_DEPT (EMP_NAME, DEPT_NAME)
AS SELECT EMPNAME, DEPTNAME
FROM EMPLOYEE, DEPARTMENT
WHERE DNO=DEPTNO;

SELECT * FROM EMP_DEPT;

-- 실습 : 주요 데이터 사전 뷰들의 이름과 기능
SELECT * FROM USER_INDEXES;

SELECT * FROM USER_CATALOG;

SELECT * FROM USER_IND_COLUMNS;

SELECT * FROM USER_TAB_COLUMNS;

SELECT * FROM USER_VIEWS;

--실습 : 
SELECT * FROM ALL_CATALOG
WHERE OWNER = 'KIM';

-- 실습 : 
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME='EMPLOYEE';

--실습 : 통계 정보는 ANALYZE문을 사용하여 갱신할 수 있다.
ANALYZE INDEX EMPDNO_IDX
COMPUTE STATISTICS;




