CREATE TABLE STORE
(STORE_NO NUMBER NOT NULL, --매장번호(주키)
MANAGER_NO NUMBER, -- 점장번호
TOTAL_INCOME NUMBER NOT NULL,--총S`수익
SERV_QUAL NUMBER, --서비스 품질 평가(5가지 기준)
DO CHAR(10), --도
SI CHAR(10), --시
DONG CHAR(10), --동

PRIMARY KEY (STORE_NO)); 


--<매장직원>  -- 안 만들어짐 // 존재 안 한다고 나옴
CREATE TABLE STORE_STAFF
(STAFF_NO NUMBER, --매장직원번호(주키)
STORE_NO NUMBER, --매장번호(외래키)
STAFF_TITLE CHAR(10), --직급(외래키)
STAFF_NAME CHAR(10), --직원이름 
SALARY NUMBER, --월급
STAFF_PHONE CHAR(15), --직원번호
WORK_SCORE NUMBER, -- 근무평가

PRIMARY KEY (STAFF_NO), 
FOREIGN KEY(STORE_NO)REFERENCES STORE(STORE_NO),
FOREIGN KEY(STAFF_TITLE)REFERENCES TITLE(TITLE));

--<본사부서>
CREATE TABLE DEPARTMENT
(DEP_NO NUMBER, -- 부서번호(주키)
DEP_NAME CHAR(10), -- 부서이름
DEP_SCORE NUMBER, --부서실적

PRIMARY KEY (DEP_NO)); 

--<본사직원> 
CREATE TABLE EMPLOYEE
(EMP_NO NUMBER, -- 직원번호(주키)
EMP_TITLE CHAR(10),--직급이름(외래키)
DEP_NO NUMBER, --부서번호(외래키)
EMP_NAME CHAR(10), --직원이름
EMP_SALARY NUMBER, --월급
EMP_PHONE CHAR(15),--전화번호
WORK_SCORE NUMBER,--근무평가

PRIMARY KEY (EMP_NO),
FOREIGN KEY (EMP_TITLE)REFERENCES TITLE(TITLE), --<본사직원>의 직급을 참조
FOREIGN KEY (DEP_NO)REFERENCES DEPARTMENT(DEP_NO)); --<본사부서>의 부서번호(주키)를 참조

--<직급>
CREATE TABLE TITLE
(TITLE CHAR(10), --직급
PRIMARY KEY (TITLE));

--<매출결정요인>
CREATE TABLE PROFIT_FACTOR
(STORE_NO NUMBER,--매장번호(주키)
MAC_DELIVERY CHAR(10), --맥딜리버리여부
MAC_DRIVE CHAR(10), --맥드라이브여부
LABOR_COST CHAR(10), --인거비상승여부
MFY CHAR(10),--MFY여부

PRIMARY KEY (STORE_NO));

--<상권>
CREATE TABLE COMMERCIALZONE
(DO CHAR(10),--도(복합키의 키1)
SI CHAR(10), --시(복합키의 키2)
DONG CHAR(10),--동(복합키의 키3)
TRAFFIC NUMBER,--교통량
POPULATION NUMBER,--유동인구

PRIMARY KEY (DO, SI, DONG));

--<메뉴>
CREATE TABLE MENU
(MENU_NO NUMBER,--메뉴번호(주키)
MENU_NAME CHAR(10), --메뉴이름
MENU_PRICE NUMBER, --가격
SALES NUMBER,--판매량

PRIMARY KEY (MENU_NO));

--<재료>
CREATE TABLE MENU_INGREDIENT
(MENU_NO NUMBER, --메뉴번호(외래키)
INGR_NAME CHAR(10),--이름(부분키)  
INGR_PRICE NUMBER,--가격
QUANTITY NUMBER,--수량

FOREIGN KEY (MENU_NO)REFERENCES MENU(MENU_NO),
PRIMARY KEY (MENU_NO, INGR_NAME));

-- <매장별 메뉴> 
CREATE TABLE STORE_MENU
(STORE_NO NUMBER,--매장번호(외래키)
MENU_NO NUMBER, --메뉴번호(외래키)
NO NUMBER, --대리키(기본키) : 일부러 추가한 키

FOREIGN KEY (STORE_NO) REFERENCES STORE(STORE_NO),
FOREIGN KEY (MENU_NO) REFERENCES MENU(MENU_NO),
PRIMARY KEY (STORE_NO));

--<대리 테이블> : 대리키 때문에 억지로 만들어진 테이블 
CREATE TABLE SUPPORT 
(SUPPORT NUMBER, --대리키(기본키)

PRIMARY KEY (SUPPORT));

--<날짜별 판매량> 
CREATE TABLE DATE_SALES
(SUPPORT NUMBER, --대리키(기본키)
SALES_DATE DATE, --날짜(부분키)
SALES NUMBER, --판매량

PRIMARY KEY(SUPPORT, SALES_DATE)); --기본키 : 대리키랑 날짜가 합쳐져서 만들어짐

--<상권분석>
CREATE TABLE ANALYZE_ZONE
(EMP_NO NUMBER,--직원번호(외래키)
DO CHAR(10),--도(외래키) -> 주키
SI CHAR(10),--시(외래키) -> 주키
DONG CHAR(10),--동(외래키) -> 주키

PRIMARY KEY(DO,SI, DONG),
FOREIGN KEY(EMP_NO)REFERENCES EMPLOYEE(EMP_NO),
FOREIGN KEY (DO,SI,DONG) REFERENCES COMMERCIALZONE(DO, SI, DONG)
);

--<상권주변시설>
CREATE TABLE SURROUNDINGS_ZONE
(DO CHAR(10),--도(외래키)
SI CHAR(10),--시(외래키)
DONG CHAR(10),--동(외래키)
SURROUNDINGS CHAR(15),--주변시설 (다치)

FOREIGN KEY(DO, SI, DONG) REFERENCES COMMERCIALZONE(DO, SI, DONG),
PRIMARY KEY(DO,SI,DONG)
);

--<매장주변시설>
CREATE TABLE SURROUNDINGS_STORE
(STORE_NO NUMBER,--매장번호(외래키) -> 복합키1
SURROUNDING CHAR(15), --주변시설 -> 복합키2

PRIMARY KEY(STORE_NO, SURROUNDING), --복합키 : 매장번호와 주변시설 두 개가 기본키 만듬 
FOREIGN KEY(STORE_NO) REFERENCES STORE(STORE_NO)
);


INSERT INTO menu_time_test(menu_time) VALUES (TO_DATE('2018-12-01', 'YYYY-MM-DD'));
select * from menu_time_test where TO_CHAR(MENU_TIME, 'MM') = '12';